import { createClient } from '@supabase/supabase-js'
const supabaseUrl = 'https://egpdpuqjprldojtgnbko.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncGRwdXFqcHJsZG9qdGduYmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MDI0MjEsImV4cCI6MjA3NTE3ODQyMX0.sL_IGoVEPOSrqM8PbCWd9ru4yO_8xvaQp36NqYE_oj0'
const supabaseServiceRoleKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncGRwdXFqcHJsZG9qdGduYmtvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTYwMjQyMSwiZXhwIjoyMDc1MTc4NDIxfQ.DvB8uBCfGDyEMQYLKlNUXxLyuYlgC4xv9v7mKlZ3bnk';
const supabase = createClient(supabaseUrl, supabaseKey);
const supabaseAdmin = createClient(supabaseUrl, supabaseServiceRoleKey);
export { supabase, supabaseAdmin };