import { createClient } from '@supabase/supabase-js'
const supabaseUrl = 'https://aeageuyapcqnyjtjnyrb.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYWdldXlhcGNxbnlqdGpueXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5ODU3NzYsImV4cCI6MjA4NTU2MTc3Nn0.UDAT7ASpc8qgoiQOA6fEjmDvHyMYiOk9UGsEikuBqz0'
const supabaseServiceRoleKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYWdldXlhcGNxbnlqdGpueXJiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTk4NTc3NiwiZXhwIjoyMDg1NTYxNzc2fQ.W-K1SbhvHyoy6E46ifnJhWywLiL0tneT3KVkXRvrYhY';
const supabase = createClient(supabaseUrl, supabaseKey);
const supabaseAdmin = createClient(supabaseUrl, supabaseServiceRoleKey);
export { supabase, supabaseAdmin };
//Backend Inseguro, cambiar